# Generated by Django 3.2.12 on 2022-04-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_candidates_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='reference_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='refer', to='app.login'),
        ),
    ]
